### ISSUE TITLE
ram consumption of text rendering

### ISSUE THREAD

**Issue by R3D9477** [haxeui/haxeui-kha#10]
(This question just for a discussion)

Hi. I noticed how much the increased RAM consumption when I try to render some text.

For example, this application will consume ~30 mb RAM:
```
package;

import kha.System;
import kha.Assets;
import kha.Framebuffer;

import haxe.ui.Toolkit;
import haxe.ui.core.Screen;
import haxe.ui.components.Button;
import haxe.ui.macros.ComponentMacros;

class KhaApplication {
	public function new () {
		Toolkit.init();
		
		Assets.loadEverything(function() {
			var button:Button = new Button();
			
			button.top  = 10;
			button.left = 10;
			//button.text = "Click Me";
			
			Screen.instance.addComponent(button);
		});

		System.notifyOnRender(render);
	}
	
	function render (framebuffer:Framebuffer) : Void {
		framebuffer.g2.begin(true, 0xFFFFFF);
		Screen.instance.renderTo(framebuffer.g2);
		framebuffer.g2.end();
	}
}
```

but if uncomment line `//button.text = "Click Me";`, then the result application with consume ~60mb RAM (and increases with the complication of UI). Operation to display title for button "Click Me" will give additionally +30mb RAM.

[TestKhaHaxeuiProject_Button.zip](https://github.com/haxeui/haxeui-kha/files/786085/TestKhaHaxeuiProject_Button.zip)

What do you think, is this normal count of RAM for a text rendering?
Thanks.

**Comment by sh-dave** [comment]
This will most likely be the textures for components and the fonts.
Not sure how it's actually implemented but i guess the font texture will be something like 1024x1024x4 or even 2048. 
Try to add some more components. I guess size will increase a little (Texture for component), but it won't allocate another big one for the actual font.
Rendertargets sizes might get increased to power of 2 depending on target platform. So even if you have say a 100x48 button, it will actually allocate a 128x64 or even a 128x128 texture.

**Comment by R3D9477** [comment]
@sh-dave Thank you for notice!
I did several tests without haxeui and had same situation. I think that this discussion not for haxeui, but for Kha (particularly for method drawString).
