### ISSUE TITLE
DropDown can't display items list

### ISSUE THREAD

**Issue by R3D9477** [haxeui/haxeui-kha#12]
## Expected Behavior
Must be displayed list of dropdown's items.

## Current Behavior
Does not nothing after mouse click.
![bug](https://cloud.githubusercontent.com/assets/15020827/24603047/fa8141d4-1867-11e7-9861-3005dd3e6bd2.png)

## Test app / minimal test case
Sample available [here](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.4_GuiFrameworks/9.4.2_HaxeUI/9.4.2.5_haxeui-kha/9.4.2.5.1_Components/DropDown).

## Your Environment

haxe 3.4.2
kha from git
haxeui-kha from git
haxeui-core form git

Thanks.

**Comment by R3D9477** [comment]
Maybe it has something to do with [issue for method "ready()"](https://github.com/haxeui/haxeui-kha/issues/11).

**Comment by ianharrigan** [comment]
You might be right, ill check it out (probably at the weekend).

**Comment by R3D9477** [comment]
@ianharrigan works fine with haxe 3.4.2, latest haxeui-core and haxeui-kha
