### ISSUE TITLE
[BUG?] FontList has no field arial

### ISSUE THREAD

**Issue by lewislepton** [haxeui/haxeui-kha#16]
something that has just popped up trying out haxeui-kha.

this error pops up right away
`/usr/local/lib/haxe/lib/haxeui-kha/git/haxe/ui/backend/TextDisplayBase.hx:16: characters 16-34 : kha._Assets.FontList has no field arial`

this is only from having things imported & not in actual use.
```
import haxe.ui.Toolkit;
import haxe.ui.core.Screen;
import haxe.ui.containers.HBox;
import haxe.ui.components.HSlider;
```

cant seem to see what the problem is to fix it on my end. just following what i have & have seen before with getting haxeui working

cheers

**Comment by sh-dave** [comment]
just copy some arial.tff into your /assets folder

**Comment by lewislepton** [comment]
thats the weird thing. i did/do have something in assets. ill try again when i get back tonight

**Comment by ianharrigan** [comment]
Hmmm, yeah

a) if you are using labels (or text in general) something is pulling it in (ie, something in core i would guess) - so thats breaking proper DCE
b) it certainly should work

Any chance you could .zip and attach a project?

**Comment by ianharrigan** [comment]
probably this is the issue with it being pulled in: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/module.xml#L19

**Comment by lewislepton** [comment]
well... had time to look further & got it working. odd really.
also is odd that it does error even though nothing is even setup in the project, but hey ho

**Comment by RafaelOliveira** [comment]
https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/TextDisplayBase.hx#L16
There is a reference with the Arial font in the repo. Seems like a test code.

**Comment by ianharrigan** [comment]
hmmm... this is a good point. I usually work off of my templates. This seems like it might be a mistake. Ill check up making a kha project "from scratch" - i see no arial.ttf in the haxeui-kha project (it should be there)

**Comment by ianharrigan** [comment]
Does this work now?

**Comment by sh-dave** [comment]
This issue can be closed.
