### ISSUE TITLE
Font doesn't work on windows build

### ISSUE THREAD

**Issue by Fuzzipede** [haxeui/haxeui-kha#24]
I tried to use a own font for a button using css and xml and there is no text.

## Expected Behavior
Create a style and add the tag: font:"Fontname";
Use the style within the button in the xml. The button should show the text with the font.

## Current Behavior
There is no text. But it's working in HTML5

## Possible Solution
Sorry no idea right now.

## Steps to Reproduce (for bugs)
1. Use skeleton example from https://github.com/haxeui/haxeui-templates. 
2. Add a own font in ttf or use the arial.ttf from the template
3. change the  main.css to
 .big-button {
    font-size: 30px;
    font: "arial";
    width: 250px;
}
4. compile to windows

## Media

Windows build
![grafik](https://user-images.githubusercontent.com/10582473/38271760-9db80164-3787-11e8-8178-fba9f65182f7.png)

HTML5 
![grafik](https://user-images.githubusercontent.com/10582473/38271849-d618023e-3787-11e8-8235-1c36a355aca9.png)

## Test app / minimal test case
Use skeleton Template

## Context
Cannot use any font on windows target. This is bad for games if i can only use the "standard" font.

## Your Environment

* Version used: git version of haxeui-core and haxeui-kha, git version of kha
* Environment name and version (e.g. Chrome 39, node.js 5.4): Windows 10
* Operating System and version (desktop or mobile): desktop

**Comment by ianharrigan** [comment]
Hmm, strange. Do you have the font?

**Comment by Fuzzipede** [comment]
Yes. It's in my assetfolder. Or do you mean if I can send you the Font?

**Comment by ianharrigan** [comment]
Yeah, i mean can you send me the whole project, or at least the font?

Cheers,
Ian

**Comment by Fuzzipede** [comment]
It ist no freefont. But I will do it again with a freefont and send you the project.

**Comment by Fuzzipede** [comment]
Updated to the latest Kha Git Version. Now i cannot compile for windows. But here is the project! :)
[skeleton.zip](https://github.com/haxeui/haxeui-kha/files/1876917/skeleton.zip)

**Comment by ianharrigan** [comment]
Ok, so i can compile fine. But i do get the issue you mention: 

![image](https://user-images.githubusercontent.com/3024242/38336247-68eea548-3861-11e8-845a-a6114ee378b4.png)

Ill look into it.

**Comment by ianharrigan** [comment]
Interestingly you can get it workng with a module (which basically forces haxeui to use the font from a haxe resource). Add a `module.xml` to you classpath and add:

```xml
<module>
    <resources>
        <resource path="./assets" prefix="assets" />
    </resources>
</module>
```

and then in css use:
```css
.big-button {
    font-name:"assets/raspberry.ttf";
}
```

Its kinda strange though, as i would have expected kha to already have that .tff is _its_ asset list... 

![image](https://user-images.githubusercontent.com/3024242/38336467-240a95e4-3862-11e8-8d69-df45a10bd7bb.png)

**Comment by ianharrigan** [comment]
Ok, i think its fixed. For some reason Reflect.hasField returns false, even though the field is there. So ill just check for `null` on Reflect.field. In fact, ill use the Assets.fonts.get(...) as thats internal to kha (just uses reflection anyway) but at least that way if it changes in the future then its safe.

**Comment by ianharrigan** [comment]
Right, that should be fixed in latest git master. So, you no longer need a module (though you can use if you want) and you can just use:

```
font-name: raspberry;
```

in the css. 

Can you close the issue if all is well? Cheers.

**Comment by Fuzzipede** [comment]
Yeah. It works now!  Thanks for the super fast fix! 👍

**Comment by sh-dave** [comment]
[`Reflect.hasField`](https://api.haxe.org/Reflect.html#hasField) is only for anon structures, but FontList is properly typed (during macro phase). I guess thatswhy it failed.

**Comment by ianharrigan** [comment]
Right, makes sense, and worked on JS since there are no real "types" in the output presumably. Well, either way, working now, and should have been using the kha functions anyway to be honest. :)
