### ISSUE TITLE
DropDowns drop clicks

### ISSUE THREAD

**Issue by RobDangerous** [haxeui/haxeui-kha#26]
DropDowns mostly ignore clicks on the list of values. Sometimes it works but very rarely, couldn't figure out the exact circumstances. Tried to figure out what's going on but UI code is just way too complicated for me. Happens in a project I can not share but if you can't reproduce I'll try to condense it down into a proper sample project.

**Comment by ianharrigan** [comment]
Hmmm, oh yeah... isnt that strange... Looking at it now...

**Comment by ianharrigan** [comment]
Should be working now.

**Comment by RobDangerous** [comment]
That worked wonders. Thanks a lot Mr H!
