### ISSUE TITLE
Negative values do not display correctly in sliders

### ISSUE THREAD

**Issue by 5Mixer** [haxeui/haxeui-kha#48]
## Expected Behavior
Negative values should behave as positive values do.

- The slider indicator should go into the negative side of the slider.
- The slider filled region should correctly go 'backwards'

## Current Behavior
 - The slider moves with the mouse, until reaching 0, where it stops.
 - The filled region does not go into the negative half

## Steps to Reproduce (for bugs)
Create a slider and set it's `min` to `-100` and `max` to `100` - move the slider.

## Media
![output2](https://user-images.githubusercontent.com/8501694/85261351-5d8cb380-b4af-11ea-8e07-66832ed7197c.gif)

## Test app / minimal test case
```
slider.min = -200;
slider.max = 200;
```

## Context
Trying to build sliders that move with the coordinates of a cartesian point.

## Your Environment
HTML5 build on a linux system.

**Comment by ianharrigan** [comment]
Nice find, pretty sure i tested this before, but maybe this is a new issue i (re)introduced somewhere

Thanks!
Ian

**Comment by ianharrigan** [comment]
Ok, this should be fixed in latest haxeui-core, if it works for you can you close this issue please?

Cheers,
Ian

**Comment by 5Mixer** [comment]
Works excellently, thanks.
