### ISSUE TITLE
invisible component for Screen.addComponent() after some delay

### ISSUE THREAD

**Issue by sh-dave** [haxeui/haxeui-kha#52]
See the sample code here: https://github.com/sh-dave/haxeui-kha-testsuite/blob/master/src/delayedAdd/Main.hx

## Expected Behavior

The component should be visible initially, without resizing the window.

## Current Behavior

When you start the sample, nothing is shown. Only when you then resize the window, the button suddenly appears.

1. The outer `View` component contains some css styling to center the nested button. If you comment out the `style` tag, the button **will correctly** be shown initially in the top/left corner.

2. If you add the main `View` to the screen during startup, and only add the nested button after some delay, it **will also show correctly** (verifiable with the removed code in the `#if 0` sections).

## Steps to Reproduce (for bugs)

1. Clone the haxeui-kha-testsuite and open in vscode with the Kha Extension Pack installed
2. Edit the khafile.js and uncomment the line `// suite.addParameter('--main delayedAdd.Main');` to pull in the proper Main function, comment out any other that might be active.

## Your Environment
* Version used:
  - haxeui-core@5f4a1feb
  - haxeui-kha@df552b0f

* Environment name and version (e.g. Chrome 39, node.js 5.4):
  - debug-html5 build
* Operating System and version (desktop or mobile):
  - Linux + Windows Desktop
* Link to your project:
  - https://github.com/sh-dave/haxeui-kha-testsuite

**Comment by ianharrigan** [comment]
Hmmm, this is really weird... i cant think what is the difference here.

**Comment by ianharrigan** [comment]
OK, so i think i can see an issue here... if you use width / height attributes (rather than css) things seem to work, ie:

```xml
<box width="100%" height="100%" styleNames="fullscreen">
```

So looks like a bug somewhere in % applying sizes via css.

**Comment by ianharrigan** [comment]
FYI: minimal test case: http://haxeui.org/builder/?wttfru

```xml
<box style="background-color: yellow;width:100%;height:100%">
    <button text="Button" verticalAlign="center" horizontalAlign="center" />
</box>
```

**Comment by ianharrigan** [comment]
OK, this should be fixed now (playground also updated to use latest haxeui-core)... so the issue would have also reared its head if you had changed a root components % w/h, ie, if you started at 100%, and then later changed that to 50% then it would always stay at 100% (its an edge case, but a bug none-the-less)

Can you close this if you are happy its fixed?

Cheers,
Ian

**Comment by sh-dave** [comment]
Yep, seems to work fine for me now as well.
