### ISSUE TITLE
strange image scaling for Toolkit.scale > 1

### ISSUE THREAD

**Issue by sh-dave** [haxeui/haxeui-kha#58]
## Expected Behavior

When using Toolkit.scale greater than 1.0 (trying to get a decent sized ui for an android test build), the image component gets smaller for some reason. I expected the image to stay the same size, only the button should get bigger?

(What i originally wanted to use is actually the styles `background-image: xxx.png` property. But this one doesn't allow to specify the `scaleMode` (fit, fill, fitinside, ...) for when the component size doesn't match the image dimensions, so i tried with an image component as a quick "fix". Should i add another issue/feature request for this?)

## Current Behavior

Toolkit.scale = 1.0

![Screenshot_2021-10-26_14-01-34](https://user-images.githubusercontent.com/13007175/138873914-1c43d489-958b-45de-bca6-9f1f32259862.png)

Toolkit.scale = 2.0

![Screenshot_2021-10-26_14-01-18](https://user-images.githubusercontent.com/13007175/138874374-ed78499a-53fd-4565-9194-0b3a6f7723ca.png)

Toolkit.scale = 3.0

![Screenshot_2021-10-26_14-02-02](https://user-images.githubusercontent.com/13007175/138874522-a9c991cd-3b99-4dfb-aa69-97d9a2a53d21.png)

## Steps to Reproduce (for bugs)

```
@:xml('
<box styleNames="my-view">
	<style>
		.my-view {
			width: 100%;
			height: 100%;
		}

		.logo {
			width: 100%;
			height: 100%;
		}
	</style>

	<image resource="big_kha_Logo.png" styleNames="logo" />
	<button text="CLICK" styleNames="click-me" />
</box>'
)
private class View extends Box {
	public function new() {
		super();
	}
}

class Main {
	public static function main() {
		kha.System.start({ width: Std.int(632 / 2), height: Std.int(612 / 2) }, function( _ ) {
			kha.Assets.loadEverything(function() {
				haxe.ui.Toolkit.theme = 'dark';
				haxe.ui.Toolkit.init({});
				haxe.ui.core.Screen.instance.addComponent(new View());
				haxe.ui.core.Screen.instance.options.noBatch = true;
				haxe.ui.Toolkit.scale = 3.0;

				kha.System.notifyOnFrames(function( fbs ) {
					final fb = fbs[0];
					final g2 = fb.g2;

					g2.begin(true, 0xff004040);
						haxe.ui.core.Screen.instance.renderTo(g2);
					g2.end();
				});
			});
		});
	}
}
```

## Your Environment

latest git everything

**Comment by sh-dave** [comment]
Any insights?

**Comment by ianharrigan** [comment]
Sorry, totally forgot about this, ill have a play now.

**Comment by ianharrigan** [comment]
Im actually getting an error on a kha js project:

```
MouseHelper.hx:24 Uncaught TypeError: Cannot read properties of undefined (reading 'notify')
    at Function.haxe_ui_backend_kha_MouseHelper.init (MouseHelper.hx:24)
    at haxe_ui_core_Screen.haxe_ui_backend_ScreenImpl [as __class__] (ScreenImpl.hx:26)
    at new haxe_ui_core_Screen (Screen.hx:25)
    at Function.haxe_ui_core_Screen.get_instance (Screen.hx:14)
    at Function.haxe_ui_Toolkit.get_screen (Toolkit.hx:103)
    at Function.haxe_ui_Toolkit.init (Toolkit.hx:79)
    at haxe_ui_HaxeUIApp.init (HaxeUIApp.hx:32)
    at haxe_ui_HaxeUIApp.ready (HaxeUIApp.hx:23)
    at Function.Main.main (Main.hx:8)
    at SyncBuilder.hx:9
```
:/

EDIT `Mouse.get()` is returning null

**Comment by ianharrigan** [comment]
OK, that should be fixed now. Can you close if this is working now?

Cheers!
Ian

**Comment by sh-dave** [comment]
Works now, thanks!
