### ISSUE TITLE
Skeleton (from haxeui-templates) Compilation Failed

### ISSUE THREAD

**Issue by R3D9477** [haxeui/haxeui-kha#6]
## Expected Behavior
Can't compile [Kha-Sample](https://github.com/haxeui/haxeui-templates/tree/master/kha/skeleton) for Linux. It's failed with error:
`/home/username/.haxelib_repo/haxeui-kha/git/haxe/ui/backend/ComponentBase.hx:13: characters 7-20 : You cannot access the js package while targeting cpp (for js.html.Image)`

I'm tried to compile this sample with KodeStudio (F5 -> Compile Kha Project -> Linux).

## Your Environment
* haxeui-core from git
* haxeui-kha from git
* haxe 3.4.0
* hxcpp 3.4.49
* kha 16.1.2
* Linux Mint 18.1 x64

Thanks.

**Comment by R3D9477** [comment]
Sorry. I have not noticed message "Important Note: currently in the alpha release of haxeui-kha only the Kha HTML5 renderer is supported, using different renderer will most likely cause compilation errors."

**Comment by sh-dave** [comment]
There were some changes in Kha recently in regards to handling the haxe.Resource stuff haxeui uses for asset handling. And i think RafaelOliveira actually managed to do a native build (not sure if Windows or Linux). So you might reopen this one until we figure it out?

Things i noticed:
- kha 16.1.2 
  - don't use Kha from haxelib, thats severly outdated. use the git version
- hxcpp 3.4.49
  - kha doesn't use haxelib's hxcpp, but bundles it's own

@RafaelOliveira care to explain a bit more of what you did to get it working?

**Comment by R3D9477** [comment]
@sh-dave Thanks for answer and your notice

**Comment by ianharrigan** [comment]
Sounds promising. Im going to be out of the loop for a little while, but will pick this up when things settle a little.

Cheers guys,
Ian

**Comment by RafaelOliveira** [comment]
@r3d9u11 you can remove the line 13 in haxe/ui/backend/ComponentBase.hx. It seems like it's a typo.
https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/ComponentBase.hx#L13 (the js import)
That was the only thing I needed to do to compile.

**Comment by R3D9477** [comment]
@RafaelOliveira Thanks for hint! I just changed line 13 to:
```
#if js
	import js.html.Image;
#end
```
And it works fine!
![1](https://cloud.githubusercontent.com/assets/15020827/23056083/8eba3176-f4fa-11e6-963e-44efcd48cb07.png)

**Comment by ianharrigan** [comment]
Im going to repon this, as i think @RafaelOliveira suggest is more correct, ie, rmove the line in the backend itself.

**Comment by R3D9477** [comment]
Thanks to all for help!

**Comment by sh-dave** [comment]
I think Ian reopened this as a reminder to actually fix it in the backend :stuck_out_tongue_winking_eye:

**Comment by ianharrigan** [comment]
Im going to close this now. Backend has been updated.
