### ISSUE TITLE
Setting Image Resource to Render Target Created Image Has Glitch

### ISSUE THREAD

**Issue by XANOZOID** [haxeui/haxeui-kha#61]
## Expected Behavior
You can update / change the image resource to update the current image any number of times without encountering bugs.

## Current Behavior
Sometimes creating an image with a RenderTarget based `kha.Image` you get graphical anomalies.

## Possible Solution
Not necessarily a possible solution, but I made sure the Image provided to the image resource was not showing graphical issues by drawing it manually and it wasn't broken like the HaxeUI Image was.

## Steps to Reproduce (for bugs)
1. Create an image component and add it to the screen
2. Create a kha render target and render images to it using g2.begin/end
3. Set the image component resource variant equal to the new image
4. repeat steps 2 and 3 a few times and you should see that there's an error

## Media
![image](https://user-images.githubusercontent.com/29788070/231058944-6d543e9a-6511-4244-ac35-5e3d55103c17.png)
![image](https://user-images.githubusercontent.com/29788070/231058974-6cee3599-ea22-4ce8-b5b8-438879320bab.png)

## Test app / minimal test case
Will create if the above information doesn't reveal the issue.

## Context
Trying to have a section of the GUI display a small version of the map.

## Your Environment
* Version used: Latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): Kha debug mode (I believe Electron)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: I can invite you

**Comment by XANOZOID** [comment]
This is not HaxeUI specific apparently.

**Comment by ianharrigan** [comment]
oh... dunno if thats a good or bad thing...
