### ISSUE TITLE
can't see text of button with default style

### ISSUE THREAD

**Issue by R3D9477** [haxeui/haxeui-kha#7]
Hi. Why I can't see text of the button (with default styling)?

## Expected Behavior

Result Window:
![123](https://cloud.githubusercontent.com/assets/15020827/23063402/6f26288a-f51b-11e6-9984-554f97d7e819.png)

if the flag "Breakpoint on All Exceptions" is checked (KodeStudio), then my application will be stopped:
![1](https://cloud.githubusercontent.com/assets/15020827/23063443/a916d288-f51b-11e6-8c14-94a4454b28bf.png)

## Test app / minimal test case
[SampleProject.zip](https://github.com/haxeui/haxeui-kha/files/783030/TestKhaHaxeuiProject_Button.zip)
Source of KhaApplication.hx:
```
package;

import kha.System;
import kha.Framebuffer;

import haxe.ui.Toolkit;
import haxe.ui.core.Screen;
import haxe.ui.components.Button;
import haxe.ui.macros.ComponentMacros;

class KhaApplication {
	public function new () {
		Toolkit.init();
		
		var button:Button = new Button();
		
		button.top  = 10;
		button.left = 10;
		button.text = "Click Me";
		
		Screen.instance.addComponent(button);

		System.notifyOnRender(render);
	}
	
	function render (framebuffer:Framebuffer) : Void {
		framebuffer.g2.begin(true, 0xFFFFFF);
		Screen.instance.renderTo(framebuffer.g2);
		framebuffer.g2.end();
	}
}
```

## Your Environment
* haxe 3.4.0
* haxeui-core from git
* haxeui-kha from git
* KodeStudio and Kha from git

Thanks.

**Comment by ianharrigan** [comment]
My first guess is that there is no font. If you take a look in `AppBase` which is the backend specific counter part of `HaxeUIApp` (https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/AppBase.hx) there is an `Assets.loadEverything(assetsLoaded);`

Of course, you dont have to use HaxeUIApp (its a helper), but you will need a font. In the templates there should be one included ("arial"), if you choose to use a different one you will need to let haxeui know that the controls (Label and TextField specifically) need to use that. To do that, checkout:

* https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/module.xml (this defines a module and packages in the .css files and then says to use them in the default theme)
* https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/kha/_module/styles/default/main.css (this is the css that instructs labels and textfields to use that font)

You could also do it in code (i think) with something like: 

`Toolkit.styleSheet.addRules(".label { font-name: ... }")`

And bypass the whole `module.xml` part all together.

**Comment by ianharrigan** [comment]
Although, ive just noticed this: https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/TextDisplayBase.hx#L15, which means if you include "arial" and load it, it should work. Wonder howcome you dont get an error though? something like "arial" doesnt exist... 

EDIT: Ok, because probably it is part of your build (its in your sample project), but its just not being loaded with `Assets.loadEverything(...)` . Either way, i think maybe that default to "arial" should probably be smarter somehow.

**Comment by ianharrigan** [comment]
So yes, to confirm, something like this works: 

```haxe
class KhaApplication {
    public function new () {
        Toolkit.init();
		
        Assets.loadEverything(function() {
            var button:Button = new Button();
            
            button.top  = 10;
            button.left = 10;
            button.text = "Click Me";
            
            Screen.instance.addComponent(button);

            System.notifyOnRender(render);
        });
    }
	
    function render (framebuffer:Framebuffer) : Void {
        framebuffer.g2.begin(true, 0xFFFFFF);
        Screen.instance.renderTo(framebuffer.g2);
        framebuffer.g2.end();
    }
}
```

![image](https://cloud.githubusercontent.com/assets/3024242/23069436/ba0f37ae-f527-11e6-8151-e19e7e7f84b5.png)

**Comment by R3D9477** [comment]
Thanks!
