### ISSUE TITLE
Clip rect broken on both html5 and windows

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-kha#8]
Kha now compiles successfully to windows, however, when using a scrollview the content isnt clipped as is should be. This happens on html5 also. 

## Expected Behavior
The contents of the ScrollView should be successfully clipped to the parents size (this used to work)

## Possible Solution
Ask Rob. :)

## Media
Windows (cpp):
![image](https://cloud.githubusercontent.com/assets/3024242/23070148/680b431e-f52a-11e6-8320-1caefe27dc54.png)

Html5:
![image](https://cloud.githubusercontent.com/assets/3024242/23070178/7c451d14-f52a-11e6-8a4d-0c7bf82ef223.png)

## Test app / minimal test case
```haxe
            var scrollview:ScrollView = new ScrollView();
            scrollview.width = 100;
            scrollview.height = 100;
            for (a in 0...20) {
                var button = new Button();
                button.text = "Button " + a;
                scrollview.addComponent(button);
            }
            Screen.instance.addComponent(scrollview);
```

## Your Environment
Latest Kha (git)
Latest HaxeUI (git)
Haxe 3.2.1

**Comment by sh-dave** [comment]
Yes, it's still an issue afaik: https://github.com/Kode/Kha/issues/424

**Comment by ianharrigan** [comment]
This is fixed for me now. Ill close (feel free to reopen if its still an issue for you)
