### ISSUE TITLE
No images in windows builds

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-kha#9]
Icons included in the default styles (which end up as haxe resources) are not showing. This is because currently there isnt a method to extract them and turn them into `kha.Image`. See: https://github.com/haxeui/haxeui-kha/blob/master/haxe/ui/backend/AssetsBase.hx#L36

## Expected Behavior
That it should be possible to turn haxe resources (bytes) into usable and valid kha images

## Possible Solution
Either dig into kha and see how it does it or ask Rob (as usual!), he mentioned some time ago about possibly exposing functions to handle this, may or may not have already happened. Need to investigate

## Steps to Reproduce (for bugs)
Add a scrollbar, no up/down images as there are in html5. 

## Media

![image](https://cloud.githubusercontent.com/assets/3024242/23070337/1dbbff6e-f52b-11e6-8749-9ed4c52060a3.png)

## Your Environment
Latest kha (git)
Latest HaxeUI (git)
Haxe 3.2.1

**Comment by sh-dave** [comment]
Try kha.Image.fromEncodedBytes(), you should be able to just drop some PNG bytes into it (not sure it's implemented for every target yet).

To use raw data, there is also kha.Image.fromBytes().

**Comment by ianharrigan** [comment]
Nice, thanks for the info, ill give it a try at somepoint.
